18:
    mode: OUTPUT
    initial: 0
    dutycycle: 100

23:
    mode: OUTPUT
    initial: 0
    dutycycle: 0

17:
    mode: OUTPUT
    initial: 0
    dutycycle:

27:
    mode: OUTPUT
    initial: 0
    dutycycle:

22:
    mode: OUTPUT
    initial: 0
    dutycycle:

24:
    mode: OUTPUT
    initial: 0
    dutycycle:
